// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Weibo.Models
{

    public partial class CampainsData
    {
        public class Datum
        {
            public double commissionRate;
            public int CampaignID;
            public int ExistStatus;
            public string CampaignName;
            public string CampaignType;
            public string AvgCommission;
            public bool Exist;
            public int manualAudit;
            public int ShopKeeperID;
            public string Properties;
        }
    }

    public partial class CampainsData
    {
        public class Info2
        {
            public object message;
            public bool ok;
        }
    }

    public partial class CampainsData
    {
        public Datum[] data;
        public Info2 info;
        public bool ok;
        public object invalidKey;
    }

}
