// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Weibo.Models
{

    public partial class SignalWeiboData
    {
        public class User2
        {
            public long id { get; set; }
            public string screen_name { get; set; }
            public string profile_image_url { get; set; }
            public string profile_url { get; set; }
            public int statuses_count { get; set; }
            public bool verified { get; set; }
            public int verified_type { get; set; }
            public string description { get; set; }
            public string gender { get; set; }
            public int mbtype { get; set; }
            public int urank { get; set; }
            public int mbrank { get; set; }
            public bool follow_me { get; set; }
            public bool following { get; set; }
            public int followers_count { get; set; }
            public int follow_count { get; set; }
            public string cover_image_phone { get; set; }
        }
    }

    public partial class SignalWeiboData
    {
        public class Visible2
        {
            public int type { get; set; }
            public int list_id { get; set; }
        }
    }

    public partial class SignalWeiboData
    {
        public class Geo2
        {
            public int width { get; set; }
            public int height { get; set; }
            public bool croped { get; set; }
        }
    }

    public partial class SignalWeiboData
    {
        public class Geo3
        {
            public string width { get; set; }
            public string height { get; set; }
            public bool croped { get; set; }
        }
    }

    public partial class SignalWeiboData
    {
        public class Large2
        {
            public string size { get; set; }
            public string url { get; set; }
            public Geo3 geo { get; set; }
        }
    }

    public partial class SignalWeiboData
    {
        public class Pic
        {
            public string pid { get; set; }
            public string url { get; set; }
            public string size { get; set; }
            public Geo2 geo { get; set; }
            public Large2 large { get; set; }
        }
    }

    public partial class SignalWeiboData
    {
        public class Status2
        {
            public string created_at { get; set; }
            public string id { get; set; }
            public string mid { get; set; }
            public string idstr { get; set; }
            public string text { get; set; }
            public int textLength { get; set; }
            public int source_allowclick { get; set; }
            public int source_type { get; set; }
            public string source { get; set; }
            public int appid { get; set; }
            public bool favorited { get; set; }
            public bool truncated { get; set; }
            public string in_reply_to_status_id { get; set; }
            public string in_reply_to_user_id { get; set; }
            public string in_reply_to_screen_name { get; set; }
            public string[] pic_ids { get; set; }
            public string thumbnail_pic { get; set; }
            public string bmiddle_pic { get; set; }
            public string original_pic { get; set; }
            public object geo { get; set; }
            public User2 user { get; set; }
            public int reposts_count { get; set; }
            public int comments_count { get; set; }
            public int attitudes_count { get; set; }
            public bool isLongText { get; set; }
            public int mlevel { get; set; }
            public Visible2 visible { get; set; }
            public int biz_feature { get; set; }
            public int hasActionTypeCard { get; set; }
            public object[] darwin_tags { get; set; }
            public object[] hot_weibo_tags { get; set; }
            public object[] text_tag_tips { get; set; }
            public int userType { get; set; }
            public int positive_recom_flag { get; set; }
            public string gif_ids { get; set; }
            public int is_show_bulletin { get; set; }
            public int ok { get; set; }
            public string status_title { get; set; }
            public Pic[] pics { get; set; }
            public string bid { get; set; }
            public string scheme { get; set; }
            public bool tipScheme { get; set; }
        }
    }

    public partial class SignalWeiboData
    {
        public Status2 status { get; set; }
        public string hotScheme { get; set; }
        public string appScheme { get; set; }
        public bool callUinversalLink { get; set; }
        public bool callWeibo { get; set; }
        public bool hit { get; set; }
    }

}
