// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace QQSpace
{

    public partial class NHPicData
    {
        public class UrlList
        {
            public string url;
        }
    }

    public partial class NHPicData
    {
        public class LargeImage
        {
            public int width;
            public int r_height;
            public int r_width;
            public UrlList[] url_list;
            public string uri;
            public int height;
        }
    }

    public partial class NHPicData
    {
        public class User2
        {
            public bool is_following;
            public string avatar_url;
            public object user_id;
            public string name;
            public bool user_verified;
        }
    }

    public partial class NHPicData
    {
        public class Activity2
        {
        }
    }

    public partial class NHPicData
    {
        public class UrlList2
        {
            public string url;
        }
    }

    public partial class NHPicData
    {
        public class MiddleImage
        {
            public int width;
            public int r_height;
            public int r_width;
            public UrlList2[] url_list;
            public string uri;
            public int height;
        }
    }

    public partial class NHPicData
    {
        public class UrlList3
        {
            public string url;
        }
    }

    public partial class NHPicData
    {
        public class s360pVideo
        {
            public int width;
            public UrlList3[] url_list;
            public string uri;
            public int height;
        }
    }

    public partial class NHPicData
    {
        public class UrlList4
        {
            public string url;
        }
    }

    public partial class NHPicData
    {
        public class OriginVideo
        {
            public int width;
            public UrlList4[] url_list;
            public string uri;
            public int height;
        }
    }

    public partial class NHPicData
    {
        public class UrlList5
        {
            public string url;
        }
    }

    public partial class NHPicData
    {
        public class s720pVideo
        {
            public int width;
            public UrlList5[] url_list;
            public string uri;
            public int height;
        }
    }

    public partial class NHPicData
    {
        public class UrlList6
        {
            public string url;
        }
    }

    public partial class NHPicData
    {
        public class s480pVideo
        {
            public int width;
            public UrlList6[] url_list;
            public string uri;
            public int height;
        }
    }

    public partial class NHPicData
    {
        public class Gifvideo2
        {
            public s360pVideo s360p_video;
            public OriginVideo origin_video;
            public s720pVideo s720p_video;
            public string mp4_url;
            public int video_height;
            public s480pVideo s480p_video;
            public string cover_image_uri;
            public double duration;
            public int video_width;
        }
    }

    public partial class NHPicData
    {
        public class Group2
        {
            public string text;
            public int create_time;
            public object id;
            public int favorite_count;
            public int go_detail_count;
            public int user_favorite;
            public int share_type;
            public double max_screen_width_percent;
            public int is_can_share;
            public int comment_count;
            public string share_url;
            public int label;
            public string content;
            public int category_type;
            public string id_str;
            public int media_type;
            public int share_count;
            public int type;
            public int status;
            public int has_comments;
            public LargeImage large_image;
            public int user_bury;
            public string status_desc;
            public User2 user;
            public int user_digg;
            public int online_time;
            public string category_name;
            public bool category_visible;
            public int bury_count;
            public bool is_anonymous;
            public int repin_count;
            public double min_screen_width_percent;
            public int digg_count;
            public int has_hot_comments;
            public int image_status;
            public int user_repin;
            public Activity2 activity;
            public object group_id;
            public MiddleImage middle_image;
            public int category_id;
            public int? is_gif;
            public Gifvideo2 gifvideo;
        }
    }

    public partial class NHPicData
    {
        public class Comment
        {
            public int status;
            public string user_profile_url;
            public int is_digg;
            public object user_id;
            public string description;
            public int bury_count;
            public string avatar_url;
            public string text;
            public object comment_id;
            public bool user_verified;
            public int digg_count;
            public string user_profile_image_url;
            public string platform_id;
            public string platform;
            public int create_time;
            public int user_digg;
            public object group_id;
            public string user_name;
            public object id;
            public int user_bury;
        }
    }

    public partial class NHPicData
    {
        public class Datum
        {
            public Group2 group;
            public Comment[] comments;
            public int type;
            public long display_time;
            public long online_time;
        }
    }

    public partial class NHPicData
    {
        public Datum[] data;
        public int max_time;
    }

}
