// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Weibo.Models
{

    public partial class AlimamaSearchShopData
    {
        public class Paginator2
        {
            public int length { get; set; }
            public int offset { get; set; }
            public int page { get; set; }
            public int beginIndex { get; set; }
            public int endIndex { get; set; }
            public int items { get; set; }
            public int lastPage { get; set; }
            public int itemsPerPage { get; set; }
            public int previousPage { get; set; }
            public int nextPage { get; set; }
            public int pages { get; set; }
            public int firstPage { get; set; }
            public int[] slider { get; set; }
        }
    }

    public partial class AlimamaSearchShopData
    {
        public class Pagelist2
        {
            public object address { get; set; }
            public object status { get; set; }
            public int memberID { get; set; }
            public int userTag { get; set; }
            public object oriMemberId { get; set; }
            public string shopTitle { get; set; }
            public string pictUrl { get; set; }
            public int shopType { get; set; }
            public object updateTime { get; set; }
            public object minCommissionRate { get; set; }
            public object maxCommissionRate { get; set; }
            public string extNick { get; set; }
            public int sellerSum { get; set; }
            public object promotedType { get; set; }
            public object starts { get; set; }
            public string shopUrl { get; set; }
            public int shopCommissionRate { get; set; }
            public string cpashop { get; set; }
            public object shopKeeperCardURL { get; set; }
            public object epcUpdateTime { get; set; }
            public object exLevel { get; set; }
            public object sortRank { get; set; }
            public object exSysType { get; set; }
            public object isJoinedCps { get; set; }
            public int shopCatID { get; set; }
            public string shopCatName { get; set; }
            public object shopEpc { get; set; }
            public int shopAuctionCount { get; set; }
            public int totalAction { get; set; }
            public string rankIcon { get; set; }
            public object rptCpsSh30dDTO { get; set; }
            public object bonusCouponDTO { get; set; }
            public object sellerEventDTO { get; set; }
            public string bonus { get; set; }
            public string coupon { get; set; }
            public string sellerevent { get; set; }
        }
    }

    public partial class AlimamaSearchShopData
    {
        public class Data2
        {
            public Paginator2 paginator { get; set; }
            public string searchurl { get; set; }
            public Pagelist2[] pagelist { get; set; }
        }
    }

    public partial class AlimamaSearchShopData
    {
        public class Info2
        {
            public object message { get; set; }
            public string pvid { get; set; }
            public bool ok { get; set; }
        }
    }

    public partial class AlimamaSearchShopData
    {
        public Data2 data { get; set; }
        public Info2 info { get; set; }
        public bool ok { get; set; }
        public object invalidKey { get; set; }
    }

}
