// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Weibo.Models;

namespace Weibo.Models
{

    public class CardlistInfo
    {

        [JsonProperty("containerid")]
        public string Containerid { get; set; }

        [JsonProperty("v_p")]
        public int VP { get; set; }

        [JsonProperty("show_style")]
        public int ShowStyle { get; set; }

        [JsonProperty("total")]
        public int Total { get; set; }

        [JsonProperty("page")]
        public int Page { get; set; }
    }

    public class User
    {

        [JsonProperty("id")]
        public object Id { get; set; }

        [JsonProperty("screen_name")]
        public string ScreenName { get; set; }

        [JsonProperty("profile_image_url")]
        public string ProfileImageUrl { get; set; }

        [JsonProperty("profile_url")]
        public string ProfileUrl { get; set; }

        [JsonProperty("statuses_count")]
        public int StatusesCount { get; set; }

        [JsonProperty("verified")]
        public bool Verified { get; set; }

        [JsonProperty("verified_type")]
        public int VerifiedType { get; set; }

        [JsonProperty("verified_type_ext")]
        public int VerifiedTypeExt { get; set; }

        [JsonProperty("verified_reason")]
        public string VerifiedReason { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("mbtype")]
        public int Mbtype { get; set; }

        [JsonProperty("urank")]
        public int Urank { get; set; }

        [JsonProperty("mbrank")]
        public int Mbrank { get; set; }

        [JsonProperty("follow_me")]
        public bool FollowMe { get; set; }

        [JsonProperty("following")]
        public bool Following { get; set; }

        [JsonProperty("followers_count")]
        public int FollowersCount { get; set; }

        [JsonProperty("follow_count")]
        public int FollowCount { get; set; }

        [JsonProperty("cover_image_phone")]
        public string CoverImagePhone { get; set; }
    }

    public class Visible
    {

        [JsonProperty("type")]
        public int Type { get; set; }

        [JsonProperty("list_id")]
        public int ListId { get; set; }
    }

    public class Geo
    {

        [JsonProperty("width")]
        public int Width { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("croped")]
        public bool Croped { get; set; }
    }

    public class Geo2
    {

        [JsonProperty("width")]
        public string Width { get; set; }

        [JsonProperty("height")]
        public string Height { get; set; }

        [JsonProperty("croped")]
        public bool Croped { get; set; }
    }

    public class Large
    {

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("geo")]
        public Geo2 Geo { get; set; }
    }

    public class Pic
    {

        [JsonProperty("pid")]
        public string Pid { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("geo")]
        public Geo Geo { get; set; }

        [JsonProperty("large")]
        public Large Large { get; set; }
    }

    public class User2
    {

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("screen_name")]
        public string ScreenName { get; set; }

        [JsonProperty("profile_image_url")]
        public string ProfileImageUrl { get; set; }

        [JsonProperty("profile_url")]
        public string ProfileUrl { get; set; }

        [JsonProperty("statuses_count")]
        public int StatusesCount { get; set; }

        [JsonProperty("verified")]
        public bool Verified { get; set; }

        [JsonProperty("verified_type")]
        public int VerifiedType { get; set; }

        [JsonProperty("verified_type_ext")]
        public int VerifiedTypeExt { get; set; }

        [JsonProperty("verified_reason")]
        public string VerifiedReason { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("mbtype")]
        public int Mbtype { get; set; }

        [JsonProperty("urank")]
        public int Urank { get; set; }

        [JsonProperty("mbrank")]
        public int Mbrank { get; set; }

        [JsonProperty("follow_me")]
        public bool FollowMe { get; set; }

        [JsonProperty("following")]
        public bool Following { get; set; }

        [JsonProperty("followers_count")]
        public int FollowersCount { get; set; }

        [JsonProperty("follow_count")]
        public int FollowCount { get; set; }

        [JsonProperty("cover_image_phone")]
        public string CoverImagePhone { get; set; }
    }

    public class Visible2
    {

        [JsonProperty("type")]
        public int Type { get; set; }

        [JsonProperty("list_id")]
        public int ListId { get; set; }
    }

    public class Geo3
    {

        [JsonProperty("width")]
        public int Width { get; set; }

        [JsonProperty("height")]
        public int Height { get; set; }

        [JsonProperty("croped")]
        public bool Croped { get; set; }
    }

    public class Geo4
    {

        [JsonProperty("width")]
        public string Width { get; set; }

        [JsonProperty("height")]
        public string Height { get; set; }

        [JsonProperty("croped")]
        public bool Croped { get; set; }
    }

    public class Large2
    {

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("geo")]
        public Geo4 Geo { get; set; }
    }

    public class Pic2
    {

        [JsonProperty("pid")]
        public string Pid { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("geo")]
        public Geo3 Geo { get; set; }

        [JsonProperty("large")]
        public Large2 Large { get; set; }
    }

    public class RetweetedStatus
    {

        [JsonProperty("created_at")]
        public string CreatedAt { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("textLength")]
        public int TextLength { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("favorited")]
        public bool Favorited { get; set; }

        [JsonProperty("thumbnail_pic")]
        public string ThumbnailPic { get; set; }

        [JsonProperty("bmiddle_pic")]
        public string BmiddlePic { get; set; }

        [JsonProperty("original_pic")]
        public string OriginalPic { get; set; }

        [JsonProperty("user")]
        public User2 User { get; set; }

        [JsonProperty("reposts_count")]
        public int RepostsCount { get; set; }

        [JsonProperty("comments_count")]
        public int CommentsCount { get; set; }

        [JsonProperty("attitudes_count")]
        public int AttitudesCount { get; set; }

        [JsonProperty("isLongText")]
        public bool IsLongText { get; set; }

        [JsonProperty("visible")]
        public Visible2 Visible { get; set; }

        [JsonProperty("bid")]
        public string Bid { get; set; }

        [JsonProperty("pics")]
        public Pic2[] Pics { get; set; }
    }

    public class Mblog
    {

        [JsonProperty("created_at")]
        public string CreatedAt { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("textLength")]
        public int TextLength { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("favorited")]
        public bool Favorited { get; set; }

        [JsonProperty("thumbnail_pic")]
        public string ThumbnailPic { get; set; }

        [JsonProperty("bmiddle_pic")]
        public string BmiddlePic { get; set; }

        [JsonProperty("original_pic")]
        public string OriginalPic { get; set; }

        [JsonProperty("user")]
        public User User { get; set; }

        [JsonProperty("reposts_count")]
        public int RepostsCount { get; set; }

        [JsonProperty("comments_count")]
        public int CommentsCount { get; set; }

        [JsonProperty("attitudes_count")]
        public int AttitudesCount { get; set; }

        [JsonProperty("isLongText")]
        public bool IsLongText { get; set; }

        [JsonProperty("visible")]
        public Visible Visible { get; set; }

        [JsonProperty("mblogtype")]
        public int Mblogtype { get; set; }

        [JsonProperty("bid")]
        public string Bid { get; set; }

        [JsonProperty("pics")]
        public Pic[] Pics { get; set; }

        [JsonProperty("retweeted_status")]
        public RetweetedStatus RetweetedStatus { get; set; }
    }

    public class Card
    {

        [JsonProperty("card_type")]
        public int CardType { get; set; }

        [JsonProperty("itemid")]
        public string Itemid { get; set; }

        [JsonProperty("scheme")]
        public string Scheme { get; set; }

        [JsonProperty("mblog")]
        public Mblog Mblog { get; set; }

        [JsonProperty("show_type")]
        public int ShowType { get; set; }

        [JsonProperty("openurl")]
        public string Openurl { get; set; }
    }

}

namespace Weibo.Models
{

    public class MblogData
    {

        [JsonProperty("cardlistInfo")]
        public CardlistInfo CardlistInfo { get; set; }

        [JsonProperty("cards")]
        public Card[] Cards { get; set; }

        [JsonProperty("ok")]
        public int Ok { get; set; }

        [JsonProperty("seeLevel")]
        public int SeeLevel { get; set; }

        [JsonProperty("showAppTips")]
        public int ShowAppTips { get; set; }

        [JsonProperty("scheme")]
        public string Scheme { get; set; }
    }

}
