// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Weibo.Models
{

    public class Data
    {

        [JsonProperty("root_child_search_type")]
        public string RootChildSearchType { get; set; }

        [JsonProperty("filter_tips")]
        public int FilterTips { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }

        [JsonProperty("count")]
        public int Count { get; set; }
    }

    public class WeiboComment
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("msg")]
        public string Msg { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

}
